# Generated by Django 5.1.7 on 2025-03-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_song_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='singer',
        ),
        migrations.RemoveField(
            model_name='song',
            name='tags',
        ),
        migrations.AlterField(
            model_name='channel',
            name='music',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='history',
            name='music_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='watchlater',
            name='video_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
