# Generated by Django 5.1.7 on 2025-03-16 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_song_singer_remove_song_tags_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
